### ISSUE TITLE
Unexpected token  issue with cyber-vision lib test

### ISSUE THREAD

**Issue by musichen** [jsarafajr/react-redux-simple-app#1]
Pulled the repo. 
Made npm install. 
Then   npm run dev
Got   an error   "unexpected token"  issue with cyber vision lib test. 
     Running on Linux Elementary OS Freya  (based on ubuntu 14.04 Trusty )  x64 
                         Kernel  3.19.0-64-generic

LOG: 

```
react-redux-simple-app$ npm run dev

> cybervision-test@1.0.0 dev /home/musichen/Desktop/playground/js/react-redux-simple-app
> node server.js

/home/musichen/Desktop/playground/js/react-redux-simple-app/server.js:25
const authorsMap = authorsJSON.reduce((map, author) => {
                                                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:124:18)
    at node.js:882:3

npm ERR! Linux 3.19.0-64-generic
npm ERR! argv "/home/musichen/.nvm/versions/io.js/v1.8.4/bin/iojs" "/home/musichen/.nvm/versions/io.js/v1.8.4/bin/npm" "run" "dev"
npm ERR! node v1.8.4
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! cybervision-test@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cybervision-test@1.0.0 dev script 'node server.js'.
npm ERR! This is most likely a problem with the cybervision-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cybervision-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/musichen/Desktop/playground/js/react-redux-simple-app/npm-debug.log
```

**Comment by jsarafajr** [comment]
@musichen Hey
You are using iojs 1.8.4 that is not fully compatible with es6 features that I used in my server.js. That's why youre getting this error.
Please update your node to the latest LTS version.
